spring.application.name=motenji


#Database connection
#spring.datasource.url=jdbc:postgresql://${db_address}
#spring.datasource.username=${db_username}
#spring.datasource.password=${db_password}

#JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#R2DBC Database connection
spring.r2dbc.url=r2dbc:postgresql://${DB_ADDRESS}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}



#Security
spring.security.user.password=${PASSWORD}
logging.level.org.springframework.security=DEBUG

#logging
logging.level.org.springframework.messaging=DEBUG
